import { NotepadMenuItem } from './NotepadMenu';

export const FILE_MENU_ITEMS: Record<string, NotepadMenuItem> = {
  // newTab: {
  //   id: 1,
  //   displayName: 'New Tab',
  //   displayShortcut: 'Ctrl+N',
  //   category: 'file',
  //   isAToggle: false,
  //   isDisabled: false,
  // },
  newWindow: {
    id: 2,
    displayName: 'New Window',
    displayShortcut: 'Ctrl+Shift+N',
    category: 'file',
    isAToggle: false,
    isDisabled: false,
  },
  open: {
    id: 3,
    displayName: 'Open',
    displayShortcut: 'Ctrl+O',
    category: 'file',
    isAToggle: false,
    isDisabled: false,
  },
  save: {
    id: 4,
    displayName: 'Save',
    displayShortcut: 'Ctrl+S',
    category: 'file',
    isAToggle: false,
    isDisabled: false,
  },
  saveAs: {
    id: 5,
    displayName: 'Save As',
    displayShortcut: 'Ctrl+Shift+S',
    category: 'file',
    isAToggle: false,
    isDisabled: false,
  },
  print: {
    id: 6,
    displayName: 'Print',
    displayShortcut: 'Ctrl+P',
    category: 'file',
    isAToggle: false,
    isDisabled: false,
  },
  closeTab: {
    id: 7,
    displayName: 'Close Tab',
    displayShortcut: 'Ctrl+W',
    category: 'file',
    isAToggle: false,
    isDisabled: false,
  },
  closeWindow: {
    id: 8,
    displayName: 'Close Window',
    displayShortcut: 'Ctrl+Shift+W',
    category: 'file',
    isAToggle: false,
    isDisabled: false,
  },
} as const;

export const EDIT_MENU_ITEMS: Record<string, NotepadMenuItem> = {
  undo: {
    id: 1,
    displayName: 'Undo',
    displayShortcut: 'Ctrl+Z',
    category: 'edit',
    isAToggle: false,
    isDisabled: true,
  },
  redo: {
    id: 2,
    displayName: 'Redo',
    displayShortcut: 'Ctrl+Y',
    category: 'edit',
    isAToggle: false,
    isDisabled: true,
  },
  cut: {
    id: 3,
    displayName: 'Cut',
    displayShortcut: 'Ctrl+X',
    category: 'edit',
    isAToggle: false,
    isDisabled: true,
  },
  copy: {
    id: 4,
    displayName: 'Copy',
    displayShortcut: 'Ctrl+C',
    category: 'edit',
    isAToggle: false,
    isDisabled: true,
  },
  paste: {
    id: 5,
    displayName: 'Paste',
    displayShortcut: 'Ctrl+V',
    category: 'edit',
    isAToggle: false,
    isDisabled: false,
  },
  find: {
    id: 6,
    displayName: 'Find',
    displayShortcut: 'Ctrl+F',
    category: 'edit',
    isAToggle: false,
    isDisabled: false,
  },
} as const;

export const VIEW_MENU_ITEMS: Record<string, NotepadMenuItem> = {
  zoomIn: {
    id: 1,
    displayName: 'Zoom In',
    displayShortcut: 'Ctrl++',
    category: 'view',
    isAToggle: false,
    isDisabled: false,
  },
  zoomOut: {
    id: 2,
    displayName: 'Zoom Out',
    displayShortcut: 'Ctrl+-',
    category: 'view',
    isAToggle: false,
    isDisabled: false,
  },
  wordWrap: {
    id: 3,
    displayName: 'Word Wrap',
    displayShortcut: 'Alt+Z',
    category: 'view',
    isAToggle: true,
    isDisabled: false,
  },
  statusBar: {
    id: 4,
    displayName: 'Status Bar',
    displayShortcut: '',
    category: 'view',
    isAToggle: true,
    isDisabled: false,
  },
} as const;
